# Generated by cucumber-sinatra. (2011-12-23 15:08:34 -0500)

ENV['RACK_ENV'] = 'test'

require File.join(File.dirname(__FILE__), '..', '..', 'lib/server.rb')

require 'rubygems'
require 'bundler/setup'
Bundler.require(:test)
require 'capybara/cucumber'

Capybara.app = Sinatra::Application::new

Mail.defaults do
  delivery_method :test # don't use '='!
  Mail::TestMailer.deliveries = MailStoreAgent.new
end

class AccountsWorld
  include Capybara::DSL
  include RSpec::Expectations
  include RSpec::Matchers
end

World do |;world|
  world = AccountsWorld.new
  #STDERR.puts world.class.included_modules
  #File.open("/tmp/methods.txt", "w").puts world.methods 
end
