# Generated by cucumber-sinatra. (2011-12-23 15:08:34 -0500)

ENV['RACK_ENV'] = 'test'

require 'rubygems'
require 'bundler/setup'
Bundler.require(:test)
require 'capybara/cucumber'
require 'accounts'

Capybara.app = Sinatra::Application::new
#Capybara.app = MyWebApp.new

class AccountsWorld
  include Capybara::DSL
  include RSpec::Expectations
  include RSpec::Matchers
end

World do |;world|
  world = AccountsWorld.new
  #STDERR.puts world.class.included_modules
  #File.open("/tmp/methods.txt", "w").puts world.methods 
end
